# This is a basic workflow to help you get started with Actions

name: DOCS-autobuild

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the gh-pages branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # schedule:
  # * is a special character in YAML so you have to quote this string
  # run every night:
  # - cron: '44 2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: CI Build
        run: |
          cd website
          yarn install
          yarn build

      - name: CI Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build/simwrapper.app
          publish_branch: gh-pages
          force_orphan: true
